### ISSUE TITLE
CMake failure

### ISSUE THREAD

**Issue by ekuznetsov139** [ROCmSoftwarePlatform/rocFFT#229] opened 2019-08-03 03:37 UTC
I am attempting to build tensorflow with ROCm support on Arch Linux. (Yeah, I should just give up and dual-boot Ubuntu, I know.) I've installed 
https://aur.archlinux.org/packages/rocr-runtime/
https://aur.archlinux.org/packages/roct-thunk-interface/
https://aur.archlinux.org/packages/hcc/
https://aur.archlinux.org/packages/hip/
and I have some sort of ROCm install in /opt/rocm, including /opt/rocm/hcc, /opt/rocm/hip, /opt/rocm/lib, etc. But tensorflow won't build because it wants rocFFT, which is not installed.

Following the wiki https://github.com/ROCmSoftwarePlatform/rocFFT/wiki/Build-on-ROCM, I create the build directory, type 

CXX=/opt/rocm/hcc/bin/hcc cmake source_dir

and get the following:

 CMake Error at /opt/rocm/hcc/lib/cmake/hcc/hcc-config.cmake:41 (add_library):
   add_library cannot create imported target "hsa-runtime64" because another
   target with the same name already exists.
 Call Stack (most recent call first):
   /usr/share/cmake-3.15/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
   /opt/rocm/hip/lib/cmake/hip/hip-config.cmake:77 (find_dependency)
   CMakeLists.txt:143 (find_package)

What seems to be happening is that hcc-config.cmake gets pulled in twice, first by CMakeLists.txt line 139 "find_package(hcc REQUIRED CONFIG PATHS /opt/rocm )" and then again by CMakeLists.txt line 143 "find_package( hip REQUIRED CONFIG PATHS /opt/rocm )"), because hip tries to pull in hcc internally.

Commenting out line 139 makes the error go away and CMake successfully generates everything.

**Comment by ekuznetsov139** [comment] 2019-08-03 04:08
I just ran into the exact same issue building rocBLAS. So, either this bug is present in both places, or the rest of my system is somehow messed up. I would like to understand how it is supposed to work, so I can raise the issue with the right project.

**Comment by ekuznetsov139** [comment] 2019-08-05 02:02
I hit it again a few times, including one when I didn't even see a straightforward fix (the same cmake header was included by different routes through two different dependency chains).

In principle, that add_library() shouldn't even be there, since it is a command for building libhsa-runtime64.so from source, which we presumably don't want to do in this case. But commenting out the call to add_library() in hcc-config.cmake is not a solution, because then I get linker errors.

In the cmake developer mailing list, found the suggestion that the call to add_library should be guarded from multiple inclusion:
https://cmake.org/pipermail/cmake-developers/2011-November/014192.html
That would make it a bug in hcc, except that code comes from the part of https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/CMakeLists.txt that has not been touched for 2 years, so, either the bug has been there for 2 years and no one noticed (unlikely) or, again, I have some sort of unusual setup situation.

**Comment by malcolmroberts** [comment] 2019-08-05 16:37
Hello!  Sorry to hear you're having issues with compilation.  This may be due to an incompatibility with rocm-cmake, which we're in the process of resolving.  Could you try checking if rocm-cmake is installed?

Alternatively, this may be caused by commit 3d02d7c81a581f66d757d98ac2f41943aefddea9; try checking out 120392bc17fc445da99fcd91b95ec56aeef00823 and see if that works.

**Comment by ekuznetsov139** [comment] 2019-08-05 19:11
I did get rocm-cmake installed, but I am not sure what (if anything) I was supposed to do with it after installing. Does it replace cmake in the system or do I need to make sure I'm using it instead of system cmake?

**Comment by malcolmroberts** [comment] 2019-08-05 20:02
rocm-cmake provides cmake configuration files for rocm projects like rocfft and rocblas.  They aren't necessary for rocfft right now, and there is a conflict that we're trying to resolve.  You should be able to safely remove rocm-cmake and just compile rocfft/rocblas without it.

**Comment by malcolmroberts** [comment] 2019-08-06 16:12
As a follow-up, I didn't have any issues with a clean system, but I can reproduce issues on a system which had had rocm-cmake installed previously.  It might be a good idea to make sure that things are really uninstalled.  On Ubuntu, this is "apt install rocm-cmake && apt purge rocm-cmake".  There should be an equivalent Arch command.

**Comment by ekuznetsov139** [comment] 2019-08-06 18:23
I will uninstall rocm-cmake and see if it does anything.

**Comment by saadrahim** [comment] 2019-08-06 21:33
Hi @ekuznetsov139 ,

Thanks you for reporting the issue. rocm libraries such as rocblas and rocFFT are undergoing a lot of changes to improve the packaging system. We have introduced new bugs and are fixing old ones. I recommend that you use the last tags for the projects that have issues. When rocm 2.7 is released, these issues should be resolved. I expect 2.7 out by the of this week. 

The issue that you reported here is very similar to something fixed this weekend. I have forwarded this issue internally for them to verify. 

Best Regards,
Saad

**Comment by malcolmroberts** [comment] 2019-09-09 15:18
ROCm 2.7 has been out for a while now (and 2.8 is on the way, more fun FFTs!); have you had a chance to try with the new version?

Also note that it may be necessary to 

export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:/opt/rocm/lib/cmake/amd_comgr/

for ROCm 2.7.

**Comment by wangzhihan-scut** [comment] 2019-09-21 17:52
@ekuznetsov139 I also encountered this problem, and I find a solution from [here](https://github.com/justxi/rocm/issues/70).
rocm-cmake has a conflict with system Cmake for ROCm2.7(Newest version).
My system Cmake version is newest version——3.15.3, and there is an incompatibility with rocm-cmake. I downgrade system Cmake from 3.15.3 to the stable 3.14.6, and I find it's working.

**Closed** 2019-10-09 22:22 UTC

**Comment by malcolmroberts** [comment] 2019-10-10 15:57
I've raised this issue in HIP.  https://github.com/ROCm-Developer-Tools/HIP/issues/1521
