### ISSUE TITLE
Undefined __global__ function. on rocFFT complex 2d FFT example\n

### ISSUE THREAD

**Issue by gmaleshkov** [ROCmSoftwarePlatform/rocFFT#295] opened 2020-04-06 10:54 UTC
### What is the expected behavior
-  to compute complex FFT

### What actually happens
-  terminate called after throwing an instance of 'std::runtime_error'
  what():  Undefined __global__ function.

### How to reproduce
-  

### Environment
| Hardware | description |
|-----|-----|
| GPU | device string |
Radeon 580
 Name:                    gfx803                             
  Marketing Name:          Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]

| CPU | device string |
 Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz

| Software | version |
5.5.13-arch2-1 
| ROCK | v0.0 |
3.3.0
| ROCR | v0.0 |
3.3.0
| HCC | v0.0 |
3.3.0
| Library | v0.0 |
3.3.0

**Comment by gmaleshkov** [comment] 2020-04-07 03:52
I used test.sh in the repository and most of them works. Didn't saw any runtime errors, just hotspot freeze the kde render. Even if i add some kernel with __global__ tag like vector_add in the example works.

**Comment by feizheng10** [comment] 2020-04-07 23:10
@gmaleshkov 
I assume when you said "test.sh" it is test_all.sh in HIP example. It looks your env should be ok. As I don't have gfx 803 on hand, I could not try to reproduce your problem.
Still more questions might help to detect the problem:
- Could you build rocFFT library itself?
- How do you build the 2d example? Is this problem specific to 2d case?
- Dou you have chance to try older ROCm stack? or the build has no prblem on the old ROCm release?

**Comment by gmaleshkov** [comment] 2020-04-08 05:55
@feizheng10 
Library is compiled without any issues: warnings and errors. Strange is that, if i compile it like static all works and gives right results but when is compiled as dynamic - shows the error. I tried multiple examples even this one the repository when is dynamic trows runtime error and undefined global function when is static works correctly.

**Comment by feizheng10** [comment] 2020-04-09 02:03
First, good to hear that no problem to build the library.
From the build config, it looks like you only enabled BUILD_CLIENTS_RIDER to build.
So, I would guess the 2D example code you mentioned is not the sample code we provide in the repo. If in this case, could you try to build -DBUILD_CLIENTS_SAMPLES=ON first?

**Comment by gmaleshkov** [comment] 2020-04-11 15:00
Sorry for the delay, but apparently i can't build samples with cmake:


Make Error at clients/samples/CMakeLists.txt:38 (add_subdirectory):
  The source directory

    /home/*****/.cache/yay/rocfft/src/rocFFT-rocm-3.3/clients/samples/CMakeFiles

  does not contain a CMakeLists.txt file.

Tests and selftest works only samples gives this error.

**Comment by feizheng10** [comment] 2020-04-14 22:20
You should be able to clean your cache and print samples_subdirs after https://github.com/ROCmSoftwarePlatform/rocFFT/blob/af3d56120329332315670e7d4c3de7ece7e4169c/clients/samples/CMakeLists.txt#L35

**Comment by malcolmroberts** [comment] 2021-12-31 14:07
We haven't had any cmake issues for quite a while; I'm closing this, but please re-open if this is still an issue.

**Closed by malcolmroberts** 2021-12-31 14:07 UTC
