### ISSUE TITLE
Failing to build in a cloud env (COPR)

### ISSUE THREAD

**Issue by CosmicFusion** [ROCmSoftwarePlatform/rocFFT#375] opened 2022-09-01 13:59 UTC
### What is the expected behavior
A successful build both locally and on COPR .
-  

### What actually happens
* A successful build on the local system.
* Failed build on COPR
-

### Logs : 
* [builder-live-log](https://download.copr.fedorainfracloud.org/results/cosmicfusion/ROCm-GFX8D/fedora-36-x86_64/04803553-rocm-rocfft/builder-live.log.gz)

### How to reproduce
try to build rocfft in a chroot  where '/sys/class/kfd/kfd/topology/nodes/' doesn't exist .
-  

### Environment
| Hardware | description |
|-----|-----|
| GPU | device string | COPR BUILD SERVER
| CPU | device string | COPR BUILD SERVER

| Software | version |
|-----|-----|
| ROCR | v5.2.3 |
| HCC | HIPCC v5.2.3 |
| Library | v5.2.1 |

**Comment by evetsso** [comment] 2022-09-01 14:55
It looks like you're passing an empty AMDGPU_TARGETS value to CMake.  This causes hipcc to try to detect the available hardware and build for that.  But since no hardware is available, rocm_agent_enumerator throws an error.

Some solutions to the problem might be:
* Do not set AMDGPU_TARGETS on the CMake command line.  rocFFT will build by default for `gfx803;gfx900:xnack-;gfx906:xnack-;gfx908:xnack-;gfx90a:xnack-;gfx90a:xnack+;gfx1030`.
* Set AMDGPU_TARGETS to include at least one target architecture.

At this time, a nonempty list of targets needs to be available to CMake, when no AMD GPU hardware is present.  This list can come from the defaults in rocFFT, or from the command line, but the list cannot be empty in this situation.

I believe this solves your problem, so I'm closing the issue.  Please feel free to comment and/or reopen if you need anything further.

**Closed by evetsso** 2022-09-01 14:55 UTC

**Comment by CosmicFusion** [comment] 2022-09-01 15:25
> It looks like you're passing an empty AMDGPU_TARGETS value to CMake. This causes hipcc to try to detect the available hardware and build for that. But since no hardware is available, rocm_agent_enumerator throws an error.
> 
> Some solutions to the problem might be:
> 
> * Do not set AMDGPU_TARGETS on the CMake command line.  rocFFT will build by default for `gfx803;gfx900:xnack-;gfx906:xnack-;gfx908:xnack-;gfx90a:xnack-;gfx90a:xnack+;gfx1030`.
> * Set AMDGPU_TARGETS to include at least one target architecture.
> 
> At this time, a nonempty list of targets needs to be available to CMake, when no AMD GPU hardware is present. This list can come from the defaults in rocFFT, or from the command line, but the list cannot be empty in this situation.
> 
> I believe this solves your problem, so I'm closing the issue. Please feel free to comment and/or reopen if you need anything further.

no Sir please re-open the issue , that did not help 

[builder-log-live](https://download.copr.fedorainfracloud.org/results/cosmicfusion/ROCm-GFX8D/fedora-36-x86_64/04803683-rocm-rocfft/builder-live.log.gz)

and this is the spec file i tried to use

[rocm-rocfft](https://download.copr.fedorainfracloud.org/results/cosmicfusion/ROCm-GFX8D/fedora-36-x86_64/04803683-rocm-rocfft/rpm.spec)

**Comment by evetsso** [comment] 2022-09-01 17:24
Ok, the problem is ultimately in how hipcc calls rocm_agent_enumerator when it's not told any GPU architecture names.  Unfortunately, hipcc is used to build host code, when it does not make sense to specify any GPU architectures.

rocm_agent_enumerator is a python script that has a doc string in its main() function, describing how to work around the lack of GPU hardware in a containerized environment.

But in a nutshell: you can create a target.lst file with one architecture per line.  rocm_agent_enumerator by default will look for this file next to the rocm_agent_enumerator script itself, or you can set ROCM_TARGET_LST in the environment to point to the full path to this target.lst file.

Once target.lst is available, hipcc should start working.  This problem isn't specific to rocFFT though - any compilation done by hipcc should have the same problem in your environment.

**Comment by cgmb** [comment] 2022-09-02 07:08
@evetsso, I'm afraid your diagnosis is incorrect.
```
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/kfd/kfd/topology/nodes/'
```
is seen in many places, but it is not fatal. The error that directly causes the build failure is this problem when linking:
```
FAILED: library/src/rocfft_rtc_helper 
: && /opt/rocm/bin/hipcc -O3 -DNDEBUG  library/src/CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o library/src/CMakeFiles/rocfft_rtc_helper.dir/rtccompile.cpp.o -o library/src/rocfft_rtc_helper  /opt/rocm-5.2.3/lib/libamdhip64.so.5.2.21152-  /opt/rocm-5.2.3/llvm/lib/clang/14.0.0/lib/linux/libclang_rt.builtins-x86_64.a && :
Traceback (most recent call last):
  File "/opt/rocm-5.2.3/bin/rocm_agent_enumerator", line 257, in <module>
    main()
  File "/opt/rocm-5.2.3/bin/rocm_agent_enumerator", line 241, in main
    target_list = readFromKFD()
  File "/opt/rocm-5.2.3/bin/rocm_agent_enumerator", line 193, in readFromKFD
    for node in sorted(os.listdir(topology_dir)):
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/kfd/kfd/topology/nodes/'
g++: error: -E or -x required when input is from standard input
clang-14: error: linker (via gcc) command failed with exit code 1 (use -v to see invocation)
```
If you look closely, the failing command is:
`/opt/rocm/bin/hipcc -O3 -DNDEBUG  library/src/CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o library/src/CMakeFiles/rocfft_rtc_helper.dir/rtccompile.cpp.o -o library/src/rocfft_rtc_helper  /opt/rocm-5.2.3/lib/libamdhip64.so.5.2.21152-  /opt/rocm-5.2.3/llvm/lib/clang/14.0.0/lib/linux/libclang_rt.builtins-x86_64.a`

The problem is `/opt/rocm-5.2.3/lib/libamdhip64.so.5.2.21152-`. The format for the libhipamd file name is `libamdhip64.so.<major_version>.<minor_version>.<patch_version>-<git_version>`. Thus when the git version cannot be determined by the build system, the resulting file name ends in a dash, which is interpreted by the linker as referring to standard input.

This is https://github.com/ROCm-Developer-Tools/HIP/pull/2218, which is a bug first reported by a user in ROCm 3.9. I encountered it a few months ago and it wasted enough of my time that I decided to fix it myself. [My fix](https://github.com/ROCm-Developer-Tools/hipamd/commit/56b32604729cca08bdcf00c7a69da8a75cc95b8a) will be included in ROCm 5.3.

**Comment by CosmicFusion** [comment] 2022-09-03 11:47
> @evetsso, I'm afraid your diagnosis is incorrect.
> ```
> FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/kfd/kfd/topology/nodes/'
> ```
> is seen in many places, but it is not fatal. The error that directly causes the build failure is this problem when linking:
> ```
> FAILED: library/src/rocfft_rtc_helper 
> : && /opt/rocm/bin/hipcc -O3 -DNDEBUG  library/src/CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o library/src/CMakeFiles/rocfft_rtc_helper.dir/rtccompile.cpp.o -o library/src/rocfft_rtc_helper  /opt/rocm-5.2.3/lib/libamdhip64.so.5.2.21152-  /opt/rocm-5.2.3/llvm/lib/clang/14.0.0/lib/linux/libclang_rt.builtins-x86_64.a && :
> Traceback (most recent call last):
>   File "/opt/rocm-5.2.3/bin/rocm_agent_enumerator", line 257, in <module>
>     main()
>   File "/opt/rocm-5.2.3/bin/rocm_agent_enumerator", line 241, in main
>     target_list = readFromKFD()
>   File "/opt/rocm-5.2.3/bin/rocm_agent_enumerator", line 193, in readFromKFD
>     for node in sorted(os.listdir(topology_dir)):
> FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/kfd/kfd/topology/nodes/'
> g++: error: -E or -x required when input is from standard input
> clang-14: error: linker (via gcc) command failed with exit code 1 (use -v to see invocation)
> ```
> If you look closely, the failing command is:
> `/opt/rocm/bin/hipcc -O3 -DNDEBUG  library/src/CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o library/src/CMakeFiles/rocfft_rtc_helper.dir/rtccompile.cpp.o -o library/src/rocfft_rtc_helper  /opt/rocm-5.2.3/lib/libamdhip64.so.5.2.21152-  /opt/rocm-5.2.3/llvm/lib/clang/14.0.0/lib/linux/libclang_rt.builtins-x86_64.a`
> 
> The problem is `/opt/rocm-5.2.3/lib/libamdhip64.so.5.2.21152-`. The format for the libhipamd file name is `libamdhip64.so.<major_version>.<minor_version>.<patch_version>-<git_version>`. Thus when the git version cannot be determined by the build system, the resulting file name ends in a dash, which is interpreted by the linker as referring to standard input.
> 
> This is https://github.com/ROCm-Developer-Tools/HIP/pull/2218, which is a bug first reported by a user in ROCm 3.9. I encountered it a few months ago and it wasted enough of my time that I decided to fix it myself. [A fix for this bug](https://github.com/ROCm-Developer-Tools/hipamd/commit/56b32604729cca08bdcf00c7a69da8a75cc95b8a) will be included in ROCm 5.3.

Yes that's correct, waiting on ROCm 5.3 then

**Comment by cgmb** [comment] 2022-09-04 06:34
I see that you're packaging ROCm for Fedora Linux. Jeremy Newton (@Mystro256) and I have been facilitating the creation of ROCm packages in Fedora and Debian. Jeremy maintains a few Fedora packages himself, but he will need help to get ROCm packaged officially within Fedora. He set up a Heterogeneous Computing Special Interest Group to organize this effort, so please take a look if you're interested: https://fedoraproject.org/wiki/SIGs/HC

I believe Jeremy patched this defect when he created his experimental rocm-hip package. That may also be worth examining: https://copr.fedorainfracloud.org/coprs/mystro256/rocm-hip/

My apologies if you're already aware of all that. It's just something I've been trying to let people know about, as the effort is in need of volunteers from the Fedora community.

**Comment by CosmicFusion** [comment] 2022-09-04 06:45
> I see that you're packaging ROCm for Fedora Linux. Jeremy Newton (@Mystro256) and I have been facilitating the creation of ROCm packages in Fedora and Debian. Jeremy maintains a few Fedora packages himself, but he will need help to get ROCm packaged officially within Fedora. He set up a Heterogeneous Computing Special Interest Group to organize this effort, so please take a look if you're interested: https://fedoraproject.org/wiki/SIGs/HC
> 
> I believe Jeremy patched this defect when he created his experimental rocm-hip package. That may also be worth examining: https://copr.fedorainfracloud.org/coprs/mystro256/rocm-hip/
> 
> My apologies if you're already aware of all that. It's just something I've been trying to let people know about, as the effort is in need of volunteers from the Fedora community.

I understand thanks

**Comment by Mystro256** [comment] 2022-09-06 22:18
@awehrfritz actually has continued what I started with Fedora, and I've been trying to help out as I have time:
https://copr.fedorainfracloud.org/coprs/awehrfritz/rocm-hip/

It's more up to date and a bit cleaner.
