### ISSUE TITLE
Undefined symbol in rocfft-device

### ISSUE THREAD

**Issue by pxl-th** [ROCmSoftwarePlatform/rocFFT#376] opened 2022-09-09 09:41 UTC
Hi! I'm trying to build rocFFT for ROCm 4.2.0 in [BinaryBuilder](https://binarybuilder.org/).
But once it finishes, it cannot dlopen `librocfft-device.so.0.1` library due to:
```
ERROR: could not load library
librocfft-device.so.0.1: undefined symbol: _ZlsR14rocfft_ostreamPKc
```

Demangling it gives:
```
$ c++filt _ZlsR14rocfft_ostreamPKc
operator<<(rocfft_ostream&, char const*)
```

Here's exact line from build logs where it happens: [link](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=22011&view=logs&j=572c5e49-83d5-5271-390a-e6dc77f89c6b&t=25aa3cdb-e20d-599e-657c-8776cc8a525f&l=1711).
Can be reproduced with build scripts from https://github.com/JuliaPackaging/Yggdrasil/pull/5445.

Looking for undefined symbols via `nm -C librocfft-device.so.0.1` gives:

```
                 U operator<<(rocfft_ostream&, bool)
                 U operator<<(rocfft_ostream&, char)
                 U operator<<(rocfft_ostream&, std::ostream& (*)(std::ostream&))
                 U operator<<(rocfft_ostream&, char const*)
                 U rocfft_ostream::flush()
                 U rocfft_ostream::rocfft_ostream(int)
000000000e5b2cf0 W rocfft_ostream::~rocfft_ostream()
000000000e5b2b60 W rocfft_ostream::~rocfft_ostream()
                 U std::ctype<char>::_M_widen_init() const
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(unsigned long, unsigned long, char const*) const
                 U std::__detail::_Prime_rehash_policy::_M_need_rehash(unsigned long, unsigned long, unsigned long) const
                 U std::ostream::put(char)
                 U std::ostream::flush()
                 U std::ostream::operator<<(int)
                 U std::locale::~locale()
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)
                 U std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()
                 U std::ios_base::Init::Init()
                 U std::ios_base::Init::~Init()
                 U std::ios_base::~ios_base()
```

While same symbols in `librocfft.so` are defined:

```
0000000000046d60 T operator<<(rocfft_ostream&, bool)
0000000000046d80 T operator<<(rocfft_ostream&, char)
0000000000046c60 T operator<<(rocfft_ostream&, double)
0000000000046d50 T operator<<(rocfft_ostream&, float)
0000000000046e20 T operator<<(rocfft_ostream&, std::ostream& (*)(std::ostream&))
0000000000046db0 T operator<<(rocfft_ostream&, char const*)
```

**Comment by evetsso** [comment] 2022-09-09 14:54
Are you able to build a newer version of rocFFT instead?  This issue was fixed in ROCm 4.5, with 89347906089a8ea01ce00f0666551f5e4b417e32.

**Comment by pxl-th** [comment] 2022-09-09 21:59
> Are you able to build a newer version of rocFFT instead? This issue was fixed in ROCm 4.5, with [8934790](https://github.com/ROCmSoftwarePlatform/rocFFT/commit/89347906089a8ea01ce00f0666551f5e4b417e32).

Tried building rocFFT in ROCm 4.5.2, but the build process is getting stuck at `kernel-generator.py` script. I let it run for hours, but nothing is changing.

```
[22:21:53] [  1%] Linking CXX executable rocfft-kernel-generator
[22:21:53] cd /workspace/srcdir/rocFFT-rocm-4.5.2/build/library/src/device/generator && /usr/bin/cmake -E cmake_link_script CMakeFiles/rocfft-kernel-generator.dir/link.txt --verbose=true
[22:21:53] /workspace/destdir/hip/bin/hipcc -fuse-ld=lld -O3 -DNDEBUG CMakeFiles/rocfft-kernel-generator.dir/generator.main.cpp.o CMakeFiles/rocfft-kernel-generator.dir/generator.file.cpp.o -o rocfft-kernel-generator  /workspace/destdir/hip/lib/libamdhip64.so.4.4.22363- --hip-link --offload-arch=gfx900 -L"/workspace/destdir/llvm/lib/clang/13.0.0/include/../lib/linux" -lclang_rt.builtins-x86_64 
[22:21:53] hipcc-cmd: "/workspace/destdir/llvm/bin/clang" --driver-mode=g++ -L"/workspace/destdir/hip/lib" -lgcc_s -lgcc -lpthread -lm -lrt  --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root -B /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/* -L /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/*  -L /opt/x86_64-linux-gnu/x86_64-linux-gnu/lib64 -L /workspace/destdir/lib  -Wl,--enable-new-dtags -Wl,-rpath=/workspace/destdir/hip/lib:/workspace/destdir/lib -lamdhip64  -fuse-ld=lld -O3 -DNDEBUG CMakeFiles/rocfft-kernel-generator.dir/generator.main.cpp.o CMakeFiles/rocfft-kernel-generator.dir/generator.file.cpp.o -o "rocfft-kernel-generator" /workspace/destdir/hip/lib/libamdhip64.so.4.4.22363- --hip-link -L/workspace/destdir/llvm/lib/clang/13.0.0/include/../lib/linux -lclang_rt.builtins-x86_64 -L/workspace/destdir/llvm/bin/../lib/clang/13.0.0/lib/linux -lclang_rt.builtins-x86_64 
[22:21:53] make[2]: Leaving directory '/workspace/srcdir/rocFFT-rocm-4.5.2/build'
[22:21:53] [  1%] Built target rocfft-kernel-generator
[22:21:53] make  -f library/src/device/CMakeFiles/gen_headers_target.dir/build.make library/src/device/CMakeFiles/gen_headers_target.dir/depend
[22:21:53] make[2]: Entering directory '/workspace/srcdir/rocFFT-rocm-4.5.2/build'
[22:21:53] cd /workspace/srcdir/rocFFT-rocm-4.5.2/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /workspace/srcdir/rocFFT-rocm-4.5.2 /workspace/srcdir/rocFFT-rocm-4.5.2/library/src/device /workspace/srcdir/rocFFT-rocm-4.5.2/build /workspace/srcdir/rocFFT-rocm-4.5.2/build/library/src/device /workspace/srcdir/rocFFT-rocm-4.5.2/build/library/src/device/CMakeFiles/gen_headers_target.dir/DependInfo.cmake --color=
[22:21:53] make[2]: Leaving directory '/workspace/srcdir/rocFFT-rocm-4.5.2/build'
[22:21:53] make  -f library/src/device/CMakeFiles/gen_headers_target.dir/build.make library/src/device/CMakeFiles/gen_headers_target.dir/build
[22:21:53] make[2]: Entering directory '/workspace/srcdir/rocFFT-rocm-4.5.2/build'
[22:21:53] [  1%] Generator producing device kernels for rocfft-device
[22:21:53] cd /workspace/srcdir/rocFFT-rocm-4.5.2/build/library/src/device && python3 /workspace/srcdir/rocFFT-rocm-4.5.2/library/src/device/kernel-generator.py --pattern=all --precision=all --groups=150 --manual-small= --manual-large= --runtime-compile=OFF generate /workspace/srcdir/rocFFT-rocm-4.5.2/build/library/src/device/generator/rocfft-kernel-generator
```

**Comment by evetsso** [comment] 2022-09-10 01:36
Can you determine if it's really stuck?  For example, is anything using CPU time?  Are you doing the build on slow storage (e.g. network filesystem)?  What files are open by the python process at the time that it's stuck (i.e. what's in /proc/*pid_of_python_process*/fd), and does that change over time?

**Comment by pxl-th** [comment] 2022-09-10 18:02
`kernel-generator.py` script launches `rocfft-kernel-generator` executable with the following arguments (printed out right before launching subprocess):
```
[
'/workspace/srcdir/rocFFT-rocm-4.5.2/build/library/src/device/generator/rocfft-kernel-generator',
'-g', '150', '-p', 'all', '-t', 'none',
'--manual-small', '1,2,3,4,5,6,7,8,10,11,13,16,18,26,27,49,64,72,81,100,104,121,128,135,144,150,162,169,192,200,208,216,224,243,250,256,270,288,320,375,384,405,432,450,480,486,500,512,540,576,600,625,640,675,729,750,768,800,810,864,900,972,1000,1024,1080,1125,1152,1200,1215,1250,1280,1296,1350,1440,1458,1500,1536,1600,1620,1728,1800,1875,1920,1944,2000,2025,2048,2160,2187,2250,2304,2400,2430,2500,2560,2592,2700,2880,2916,3000,3072,3125,3200,3240,3375,3456,3600,3645,3750,3840,3888,4000,4050,4096'
]
```

`rocfft-kernel-generator` utilizes 100% of a single thread, but I never saw the end of the execution. But in any case, is it supposed to take several hours? I might try leaving it run overnight, though that doesn't look right that it takes this much time.

I'm doing build on my local machine inside the BinaryBuilder container which has access to all machine's resources.

Specs for my machine:
- CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz 
- SSD: Kingston NV1 2 TB
- RAM: 64 GB

**Comment by evetsso** [comment] 2022-09-12 15:57
No, it's not supposed to take that long.

Is it feasible for you to try rocFFT 5.0.0 or newer?  The kernel generator was moved from a python script to a c++ executable, which might fix things.

**Comment by pxl-th** [comment] 2022-09-13 09:18
> No, it's not supposed to take that long.
> 
> Is it feasible for you to try rocFFT 5.0.0 or newer? The kernel generator was moved from a python script to a c++ executable, which might fix things.

Yes, I'm now in the process of building ROCm 5.2.3. I'll post an update once I get to rocFFT.

**Comment by evetsso** [comment] 2022-10-03 16:13
@pxl-th Do you have any update?  Is this problem reproducible on 5.2.3?

**Comment by evetsso** [comment] 2022-10-17 16:20
Closing due to inactivity, and because ROCm 5.0 ought to solve this.  Please feel free to reopen if this continues to be a problem.

**Closed by evetsso** 2022-10-17 16:20 UTC
