### ISSUE TITLE
Doesn't build with cmake 3.21

### ISSUE THREAD

**Issue by haampie** [ROCmSoftwarePlatform/rocFFT#322] opened 2021-08-04 17:07 UTC
This project uses `target_compile_features` extensively, which is a good thing, but due to very poor support for hipcc/ROCMClang in cmake 3.21, I can't build this with `CXX=hipcc cmake ...`

Minimal reproducer:

```
$ cat ../CMakeLists.txt 
cmake_minimum_required(VERSION 3.0)

project(Hello)

add_executable(main main.cpp)
target_compile_features(main PRIVATE cxx_static_assert cxx_nullptr cxx_auto_type)

$ cmake --version
cmake version 3.21.1

$ hipcc --version
HIP version: 4.2.0

$ CXX=hipcc cmake ..
CMake Error at CMakeLists.txt:6 (target_compile_features):
  target_compile_features The compiler feature "cxx_static_assert" is not
  known to CXX compiler

  "ROCMClang"

  version .
```

Do you have an issue for this in cmake upstream?

**Comment by haampie** [comment] 2021-08-04 17:10
I've found https://gitlab.kitware.com/cmake/cmake/-/issues/22460

**Comment by evetsso** [comment] 2021-08-04 17:37
Right, this is ultimately a CMake issue (which you've found!), and is not specific to rocFFT.  Closing this issue.

But one potential hack around the problem is to set `__skip_rocmclang` to `ON` before the project is declared.  The check for the ROCMClang compiler is controlled by that internal variable: https://github.com/Kitware/CMake/blob/v3.21.0/Modules/CMakeCompilerIdDetection.cmake#L85

A proper fix in CMake itself would definitely be better though.

**Closed by evetsso** 2021-08-04 17:37 UTC
