### ISSUE TITLE
result of complex 3d sample is incorrect

### ISSUE THREAD

**Issue by alexschroeter** [ROCmSoftwarePlatform/rocFFT#278] opened 2019-12-10 13:31 UTC
### expected outcome
Doing a forward and backward transform consecutively should produce the original data if result is divided by size of the data.

### actual outcome
Here is the output of the provided example repo/docs/samples/ running "./complex3d 4 4 4"
`
rocFFT complex 3d FFT example
Nx: 4	Ny: 4	Nz: 4	in-place: 0
Input:
(0,0) (1,0) (2,0) (3,0) 
(1,0) (2,0) (3,0) (4,0) 
(2,0) (3,0) (4,0) (5,0) 
(3,0) (4,0) (5,0) (6,0) 

(1,0) (2,0) (3,0) (4,0) 
(2,0) (3,0) (4,0) (5,0) 
(3,0) (4,0) (5,0) (6,0) 
(4,0) (5,0) (6,0) (7,0) 

(2,0) (3,0) (4,0) (5,0) 
(3,0) (4,0) (5,0) (6,0) 
(4,0) (5,0) (6,0) (7,0) 
(5,0) (6,0) (7,0) (8,0) 

(3,0) (4,0) (5,0) (6,0) 
(4,0) (5,0) (6,0) (7,0) 
(5,0) (6,0) (7,0) (8,0) 
(6,0) (7,0) (8,0) (9,0) 

Transformed:
(-23.8431,-23.8431) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 

(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 

(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 

(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 

Transformed back:
(288,0) (-32,-32) (-32,0) (-32,32) 
(-32,-32) (0,0) (0,0) (0,0) 
(-32,0) (0,0) (0,0) (0,0) 
(-32,32) (0,0) (0,0) (0,0) 

(-32,-32) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 

(-32,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 

(-32,32) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 
(0,0) (0,0) (0,0) (0,0) 

Maximum error: 9

### Here is the result for the complex2d which works as expected "./complex2d 4 4":

rocFFT complex 2d FFT example
Nx: 4	Ny: 4	in-place: 0
Input:
(0,0) (1,0) (2,0) (3,0) 
(1,0) (2,0) (3,0) (4,0) 
(2,0) (3,0) (4,0) (5,0) 
(3,0) (4,0) (5,0) (6,0) 

Transformed:
(48,0) (-8,8) (-8,0) (-8,-8) 
(-8,8) (0,0) (0,0) (0,0) 
(-8,0) (0,0) (0,0) (0,0) 
(-8,-8) (0,0) (0,0) (0,0) 

Transformed back:
(0,0) (16,9.79717e-16) (32,0) (48,-9.79717e-16) 
(16,9.79717e-16) (32,1.95943e-15) (48,9.79717e-16) (64,0) 
(32,0) (48,9.79717e-16) (64,0) (80,-9.79717e-16) 
(48,-9.79717e-16) (64,0) (80,-9.79717e-16) (96,-1.95943e-15) 

Maximum error: 1.22465e-16
`

**Comment by malcolmroberts** [comment] 2019-12-10 15:55
Unfortunately there's a but in the 3D out-of-place routine; this looks to be a duplicate of issue 270.

**Comment by malcolmroberts** [comment] 2019-12-31 03:44
I believe that this is fixed in develop.  Would you mind giving it a try?

**Comment by malcolmroberts** [comment] 2020-01-14 20:29
I'm marking this as closed; if this is still an issue, please re-open!

**Closed by malcolmroberts** 2020-01-14 20:29 UTC
