### ISSUE TITLE
Deprecated hipfft.h header is installed from rocFFT on ROCm4.1

### ISSUE THREAD

**Issue by amathews-amd** [ROCmSoftwarePlatform/rocFFT#312] opened 2021-04-09 14:24 UTC
### What is the expected behavior
-  hipfft.h is installed from hipFFT

### What actually happens
-  hipfft.h is installed from rocFFT
See: 
https://github.com/ROCmSoftwarePlatform/rocFFT/blob/develop/library/include/hipfft.h#L26
https://github.com/ROCmSoftwarePlatform/hipFFT/commit/9b08390195840d5bdc3b2a9869ccefe86131ce46

### How to reproduce
- Pull docker images for ROCm >= 4.1
-  Check /opt/rocm/include/hipfft.h 

| Software | version |
|-----|-----|
ROCm4.1

**Comment by leofang** [comment] 2021-04-09 16:06
Thanks, Aswin! You guys probably know already, so I'm just dropping a note for future reference. The problem is the `hipfft` package should install both the header `/opt/rocm/hipfft/include/hipfft.h` and a symlink `/opt/rocm/include/hipfft.h` pointing to the former, following the convention of other hipXXX packages. 

However, in ROCm 4.1.0 the symlink is not installed by `hipfft` but instead by `rocfft`, and it points to `/opt/rocm/rocfft/include/hipfft.h`, not `/opt/rocm/hipfft/include/hipfft.h`.

**Comment by memmett** [comment] 2021-04-09 17:07
Hi @leofang, thanks for your note.  Yes, we are aware of the issue.  As you can probably imagine, we are trying to make the transition as painless as possible for a few downstream projects.

**Comment by leofang** [comment] 2021-05-20 04:35
> However, in ROCm 4.1.0 the symlink is not installed by `hipfft` but instead by `rocfft`, and it points to `/opt/rocm/rocfft/include/hipfft.h`, not `/opt/rocm/hipfft/include/hipfft.h`.

This is still not fixed in ROCm 4.2.0.

**Comment by malcolmroberts** [comment] 2021-12-31 13:55
This should be fixed as of, I believe, rocm 4.5.

**Closed by malcolmroberts** 2021-12-31 13:55 UTC
